/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test public void testRollFunction(){
        Library classUnderTest = new Library();
        int[] rollResult = classUnderTest.roll(4);
        assertEquals(rollResult.length,4);
    }
    @Test public void testcontainsDuplicatesFunction() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.containsDuplicates(new int[]{1, 2, 6, 4, 5, 1}));
    }
    @Test public void testcalcAvgFunction() {
        Library classUnderTest = new Library();
      double result = classUnderTest.calcAvg(new int[]{6,2,1});
      assertEquals(result,3.0);
    }
    @Test public void testlowAvgFunction() {
        Library classUnderTest = new Library();
        String result = Arrays.toString(classUnderTest.lowAvg(new int[][]{{0, 0, 2}, {3, 3, 3},{5,5,5,5},{1,1,1}}));
        assertEquals(result,Arrays.toString(new int[]{0, 0, 2}));
    }
}
