/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {
    public static void main(String[] args) {
        // Call the functions
        System.out.println(Arrays.toString(roll(4)));
        System.out.println(containsDuplicates(new int[]{1,2, 6, 4, 5,1}));
        System.out.println(calcAvg(new int[]{6,2,1}));
        System.out.println(Arrays.toString(lowAvg(new int[][]{{0, 0, 2}, {3, 3, 3},{5,5,5,5},{1,1,1}})));
    }

// -----------------------------------Functions-----------------------------------------------//

    /* roll function accepts an integer n and rolls a six-sided dice n times.
    The method should return an array containing the values of the rolls. */
    static int[] roll(int n){
        int[]arr=new int[n];  //Array with size n to store in it.
        for(int i =0; i<n; i++){ // looping for n time to git n number
            int randomInt = (int)(1+(6.0 * Math.random())); // get random number between 1 & 6
            arr[i]=randomInt; // store the number in the array
        }
        return arr;
    }

    /* containsDuplicates function returns true or false
     depending on whether the array contains duplicate values. */
    static boolean containsDuplicates(int[]arr){
        for(int i=0 ; i<arr.length; i++){
            for (int j = i+1 ; j<arr.length ; j++){ // looping in the array starting with the index where the last for stands
                if(arr[i]==arr[j]){
                    return true;
                }
            }

        }
        return false;
    }

    /*calcAvg method that accepts an array of integers
     and calculates and returns the average of all the values in the array.*/
    static double calcAvg(int[]a){
        double sum =0; // initial value
        for (int i=0 ; i<a.length;i++){
            sum += a[i];
        }
        double avg = sum/a.length;
        return avg;
    }
    /*lowAvg take an array of arrays calculates the average value for each
    array and return the array with the lowest average.*/
    static int[] lowAvg(int[][]arr){
        // all index is a sub array
        double[]avgArr = new double[arr.length]; // array to store the avg for all sub array

        for(int i=0; i< arr.length; i++) {
            double sum =0;// initial value for sub array
            for(int j=0; j< arr[i].length; j++) {
                sum+=arr[i][j];
            }
            double avg = sum/arr[i].length;
            avgArr[i]=avg;
        }

        double lowAvg=avgArr[0]; // initial value for the low number
        int indexofLow = 0;
        for (int i=1; i<avgArr.length;i++){
            if(avgArr[i]<lowAvg){
                lowAvg=avgArr[i]; // if any number less than the initial value it will be the lowAng
                indexofLow = i;
            }
        }
        return arr[indexofLow];

    }


    public boolean someLibraryMethod() {
        return true;
    }
}
