/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("res 1", 3);
        System.out.println(restaurant.toString());
        System.out.println("-----------------------------------");
        restaurant.addReview("nice ", "Hiba" , 5);
        System.out.println(restaurant.toString());
        System.out.println("-----------------------------------");
        restaurant.addReview("cute", "Rama" , 2);
        restaurant.addReview("not good", "Suzan" , 1);
        System.out.println(restaurant.toString());
        System.out.println("-----------------------------------");


    }

}
