/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(findError("C:\\Users\\Hiba Almade\\Desktop\\java-fundamentals\\linter\\app\\src\\main\\resources\\getas.js"));
       // System.out.println(findError("C:\\Users\\Hiba Almade\\Desktop\\java-fundamentals\\linter\\app\\src\\main\\resources\\empty.js"));
       // System.out.println(findError("C:\\Users\\Hiba Almade\\Desktop\\java-fundamentals\\linter\\app\\src\\main\\resources\\oneError.js"));
       // System.out.println(findError("C:\\Users\\Hiba Almade\\Desktop\\java-fundamentals\\linter\\app\\src\\main\\resources\\noError.js"));
       // System.out.println(findError("C:\\Users\\Hiba Almade\\Desktop\\java-fundamentals\\linter\\app\\src\\main\\resources\\fewError.js"));

    }

    static String findError(String path) {

        File file = new File(path);

        int lineNumber = 1;
        String errorMsg = "";

        try {
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                if (!line.endsWith("{") && !line.endsWith("}") && !line.endsWith(";")
                        && !line.isEmpty() && !line.contains("if") && !line.contains("else")) {
                    errorMsg+="\nLine " + lineNumber + ": Missing semicolon.";
                }
                lineNumber++;
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        }
        return errorMsg;

    }
}
