/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    Restaurant restaurant = new Restaurant("res 1", 3);

    @Test void createRestaurantTest() {
        Library classUnderTest = new Library();
        assertEquals("Restaurant name: res 1\n" +
                "Restaurant price: 3 $\n" +
                "Restaurant Stars: 0\n" +
                "Restaurant List: ",restaurant.toString());
    }
    @Test void addReviewTest() {

        restaurant.addReview("nice ", "Hiba" , 5);
        assertEquals("Restaurant name: res 1\n" +
                "Restaurant price: 3 $\n" +
                "Restaurant Stars: 5\n" +
                "Restaurant List: \n" +
                "{body: 'nice ', author: 'Hiba', stars: 5}",restaurant.toString());
    }

    @Test void updateStarsTest() {

        restaurant.addReview("cute", "Rama" , 2);
        restaurant.addReview("not good", "Suzan" , 1);
        assertEquals("Restaurant name: res 1\n" +
                "Restaurant price: 3 $\n" +
                "Restaurant Stars: 1\n" +
                "Restaurant List: \n" +
                "{body: 'cute', author: 'Rama', stars: 2}\n" +
                "{body: 'not good', author: 'Suzan', stars: 1}",restaurant.toString());
    }

}
